### ISSUE TITLE
Create a JavaScript file containing objects for generated text (fortunes)

### ISSUE THREAD

**Issue by TylerFlar** [cse110-sp23-group8/cse110-sp23-group8#3]
## Description:
We need to create a JavaScript file that contains objects for all the generated text used by our Panda Express Fortune Telling website. The focus, for now, is to make objects for bad, neutral, and good fortunes.

## Requirements:
1. Create a new JavaScript file named **'fortunes.js'** in the **'source/js'** folder.
2. Create an object for each type of fortune: bad, neutral, and good. You can create your fortunes or use ChatGPT to generate some.

Please note that branch protection is enabled, so you should create a new branch for your work. Once you have completed the task, submit a pull request for review. If you decide to work on this issue, please assign yourself to it.

Thank you for your contribution!

**Comment by pootis2** [comment]
Hello, I have added a branch that has the fortunes.js file. Can anyone check if that is enough? Also, fell free to add more.

**Comment by TylerFlar** [comment]
> Hello, I have added a branch that has the fortunes.js file. Can anyone check if that is enough? Also, fell free to add more.

Please make a pull request if done.
