### ISSUE TITLE
Music on the front page

### ISSUE THREAD

**Issue by Spriteson** [cse110-sp23-group8/cse110-sp23-group8#32]
Music for front page will auto play when using go live on local computer, but doesn't play when using the project page listed on readme.
- [ ] Need to auto play when open the website 
- [ ] Need to work on refreshed page

**Comment by World1014** [comment]
I was checking into this, apparently with Chrome after the first site load with audio playing the browser autoblocks all audio on refresh of the same page (it seems to work on Firefox on each refresh but it warns you about the autoblocking). I think these issues stem from this problem with Chrome. So we may need to just make a note about this as something we won't be able to fully fix, but if the user changes a site setting it should work (I tested this locally and it seemed to work), so this is something to think about.

**Comment by TylerFlar** [comment]
Yeah, if it's a Chrome accessibility/spam protection thing, we should make a note about it and not worry about forcing the user to hear the music all the time. It does work for the first load, and it will for the final video presentation (also doesn't break the site), so it should be ok.
