### ISSUE TITLE
Gather Assets and Use CSS/JS to integrate them into the webpage

### ISSUE THREAD

**Issue by jackmontoro** [cse110-sp23-group8/cse110-sp23-group8#4]
- [x] Get images of panda express ordering interactions
- [x] Collect images of different meals to correspond with in-game decisions
- [x] Get image of cracked fortune cookie with fortune slip showing
- [ ] Integrate these assets into the index.html page using CSS and JavaScript

**Comment by Spriteson** [comment]
cookie images relocated in masteryangz-patch1

**Comment by masteryangz** [comment]
order image and entrees images in masteryangz-patch-1

**Comment by masteryangz** [comment]
I think we just need to integrate these assets into the index.html
